### ISSUE TITLE
Implantació de SOLR per a la indexació i cerca de continguts

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#345]
Es sol·licita iniciar tasca d'implantació per a la indexació i cerca de continguts mitjançant tecnologia SOLR Entre les subtasques a realitzar en aquesta fase es destaquen:
- Definició del schema comú d'indexació
- Creació i configuració d'indexos
- Document d'instal·lació

**Comment by sgelabert-dgtic** [comment]
Tenim problemes amb la indexació de fitxes pendents. Pareix un problema amb els permisos per accedir a EJBs.

```
2016-12-05 09:24:44,075 ERROR [es.caib.rolsac.back2.util.IndexacionJob] Error indexacion pendientes
org.ibit.rol.sac.persistence.delegate.DelegateException: java.rmi.ServerException: Could not get EJBObject; nested exception is: 
	java.lang.reflect.InvocationTargetException
	at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.afterReturn(DelegateLogInterceptor.java:46)
	at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.intercept(DelegateLogInterceptor.java:97)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$2e875e2c.indexarPendientes(<generated>)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegate.indexarPendientes(SolrPendienteProcesoDelegate.java:57)
	at es.caib.rolsac.back2.util.IndexacionJob.execute(IndexacionJob.java:96)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: java.rmi.ServerException: Could not get EJBObject; nested exception is: 
	java.lang.reflect.InvocationTargetException
	at org.jboss.proxy.ejb.handle.StatelessHandleImpl.getEJBObject(StatelessHandleImpl.java:98)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegateImpl.getFacade(SolrPendienteProcesoDelegateImpl.java:43)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegateImpl.indexarPendientes(SolrPendienteProcesoDelegateImpl.java:122)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$2e875e2c.CGLIB$indexarPendientes$0$5(<generated>)
	at org.ibit.rol.sac.persistence.delegate.SolrPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$2e875e2c$$FastClassByCGLIB$$e1a7833d.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:201)
	at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.intercept(DelegateLogInterceptor.java:91)
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.proxy.ejb.handle.StatelessHandleImpl.getEJBObject(StatelessHandleImpl.java:94)
	... 11 more
Caused by: java.rmi.AccessException: SecurityException; nested exception is: 
	javax.security.auth.login.LoginException: Token de autorización no valido
	at org.jboss.ejb.plugins.LogInterceptor.handleException(LogInterceptor.java:384)
	at org.jboss.ejb.plugins.LogInterceptor.invokeHome(LogInterceptor.java:139)
	at org.jboss.ejb.plugins.ProxyFactoryFinderInterceptor.invokeHome(ProxyFactoryFinderInterceptor.java:107)
	at org.jboss.ejb.StatelessSessionContainer.internalInvokeHome(StatelessSessionContainer.java:333)
	at org.jboss.ejb.Container.invoke(Container.java:743)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.mx.server.ReflectedDispatcher.dispatch(ReflectedDispatcher.java:74)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:76)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:68)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:96)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:213)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:484)
	at org.jboss.invocation.local.LocalInvoker.invoke(LocalInvoker.java:111)
	at org.jboss.invocation.InvokerInterceptor.invokeLocal(InvokerInterceptor.java:193)
	at org.jboss.invocation.InvokerInterceptor.invoke(InvokerInterceptor.java:179)
	at org.jboss.proxy.TransactionInterceptor.invoke(TransactionInterceptor.java:61)
	at org.jboss.proxy.SecurityInterceptor.invoke(SecurityInterceptor.java:70)
	at org.jboss.proxy.ejb.HomeInterceptor.invoke(HomeInterceptor.java:188)
	at org.jboss.proxy.ClientContainer.invoke(ClientContainer.java:100)
	at com.sun.proxy.$Proxy312.create(Unknown Source)
	... 16 more
Caused by: javax.security.auth.login.LoginException: Token de autorización no valido
	at es.caib.loginModule.auth.SeyconEJBLoginModule.passwordLogin(SeyconEJBLoginModule.java:245)
	at es.caib.loginModule.auth.SeyconEJBLoginModule.login(SeyconEJBLoginModule.java:181)
	at sun.reflect.GeneratedMethodAccessor2221.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:762)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
	at org.jboss.security.plugins.JaasSecurityManager.defaultLogin(JaasSecurityManager.java:596)
	at org.jboss.security.plugins.JaasSecurityManager.authenticate(JaasSecurityManager.java:522)
	at org.jboss.security.plugins.JaasSecurityManager.isValid(JaasSecurityManager.java:331)
	at org.jboss.ejb.plugins.SecurityInterceptor.checkSecurityAssociation(SecurityInterceptor.java:163)
	at org.jboss.ejb.plugins.SecurityInterceptor.invokeHome(SecurityInterceptor.java:91)
	at org.jboss.ejb.plugins.LogInterceptor.invokeHome(LogInterceptor.java:135)
	... 36 more
```
