### ISSUE TITLE
Recuperar revisió git

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#362]
Es sol·licita incorporar informació sobre la revisió de git, versió i data de construcció en la capçalera de l'aplicació.

ROLSAC v1.3 build: 06-07-2016 08:31:39 (b44ce40)

El canvi  es semblant a la modificació sol·licitada per GUSITE (https://github.com/GovernIB/gusite/issues/25)

**Comment by sgelabert-dgtic** [comment]
Dóna un error al intentar llegir version.properties. Adjunt log del servidor d'aplicacions.

```
2016-08-03 13:00:30,506 ERROR [org.jboss.web.localhost.Engine] StandardWrapperValve[rolsacmvc]: Servlet.service() for servlet rolsacmvc threw exception
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at es.caib.rolsac.back2.controller.PantallaBaseController.loadIndexModel(PantallaBaseController.java:90)
	at es.caib.rolsac.back2.controller.QuadreControlController.quadreControl(QuadreControlController.java:192)
```
