### ISSUE TITLE
Problemes desplegament ROLSAC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#408]
Tenim errades aleatòries dins ROLSAC en temps de desplegament. Avui s'ha reiniciat els servidor de PRO i no s'ha engegat fins al sisè o setè desplegament.
Copio/aferro l'error a continuació que pareix provenir de l'execució del mètode es.caib.rolsac.back2.util.RolsacSessionListener.sessionCreated(HttpSessionEvent)

```
2017-07-11 12:24:21,505 ERROR [org.jboss.ejb.plugins.LogInterceptor] Unexpected Error in method: public abstract java.util.List org.ibit.rol.sac.persistence.intf.IdiomaFacade.listarLenguajes() throws java.rmi.RemoteException
java.lang.IllegalAccessError: org/apache/commons/collections/ReferenceMap$Entry
at org.apache.commons.collections.ReferenceMap.<init>(Unknown Source)
at org.apache.commons.collections.ReferenceMap.<init>(Unknown Source)
at net.sf.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:230)
at net.sf.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:805)
at es.caib.rolsac.persistence.hibernate.HibernateLocator.initSessionFactory(HibernateLocator.java:74)
at es.caib.rolsac.persistence.hibernate.HibernateLocator.<init>(HibernateLocator.java:37)
at es.caib.rolsac.persistence.hibernate.HibernateLocator.getInstance(HibernateLocator.java:52)
at es.caib.rolsac.persistence.hibernate.HibernateLocator.getSessionFactory(HibernateLocator.java:60)
at org.ibit.rol.sac.persistence.ejb.HibernateEJB.ejbCreate(HibernateEJB.java:105)
at org.ibit.rol.sac.persistence.ejb.IdiomaFacadeEJB.ejbCreate(IdiomaFacadeEJB.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.ejb.StatelessSessionEnterpriseContext.<init>(StatelessSessionEnterpriseContext.java:67)
at org.jboss.ejb.plugins.StatelessSessionInstancePool.create(StatelessSessionInstancePool.java:49)
at org.jboss.ejb.plugins.AbstractInstancePool.get(AbstractInstancePool.java:183)
at org.jboss.ejb.plugins.StatelessSessionInstanceInterceptor.invoke(StatelessSessionInstanceInterceptor.java:73)
at org.jboss.ejb.plugins.AbstractInterceptor.invoke(AbstractInterceptor.java:109)
at org.jboss.ejb.plugins.MetricsInterceptor.invoke(MetricsInterceptor.java:142)
at org.jboss.ejb.plugins.AbstractTxInterceptor.invokeNext(AbstractTxInterceptor.java:101)
at org.jboss.ejb.plugins.TxInterceptorCMT.runWithTransactions(TxInterceptorCMT.java:348)
at org.jboss.ejb.plugins.TxInterceptorCMT.invoke(TxInterceptorCMT.java:179)
at org.jboss.ejb.plugins.SecurityInterceptor.invoke(SecurityInterceptor.java:120)
at org.jboss.ejb.plugins.LogInterceptor.invoke(LogInterceptor.java:206)
at org.jboss.ejb.plugins.ProxyFactoryFinderInterceptor.invoke(ProxyFactoryFinderInterceptor.java:136)
at org.jboss.ejb.StatelessSessionContainer.internalInvoke(StatelessSessionContainer.java:345)
at org.jboss.ejb.Container.invoke(Container.java:723)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.mx.server.ReflectedDispatcher.dispatch(ReflectedDispatcher.java:74)
at org.jboss.mx.server.Invocation.dispatch(Invocation.java:76)
at org.jboss.mx.server.Invocation.dispatch(Invocation.java:68)
at org.jboss.mx.server.Invocation.invoke(Invocation.java:96)
at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:213)
at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:484)
at org.jboss.invocation.local.LocalInvoker.invoke(LocalInvoker.java:111)
at org.jboss.invocation.InvokerInterceptor.invokeLocal(InvokerInterceptor.java:193)
at org.jboss.invocation.InvokerInterceptor.invoke(InvokerInterceptor.java:179)
at org.jboss.proxy.TransactionInterceptor.invoke(TransactionInterceptor.java:61)
at org.jboss.proxy.SecurityInterceptor.invoke(SecurityInterceptor.java:70)
at org.jboss.proxy.ejb.StatelessSessionInterceptor.invoke(StatelessSessionInterceptor.java:115)
at org.jboss.proxy.ClientContainer.invoke(ClientContainer.java:100)
at com.sun.proxy.$Proxy246.listarLenguajes(Unknown Source)
at org.ibit.rol.sac.persistence.delegate.IdiomaDelegateImpl.listarLenguajes(IdiomaDelegateImpl.java:45)
at org.ibit.rol.sac.persistence.delegate.IdiomaDelegateImpl$$EnhancerByCGLIB$$2abe3ec.CGLIB$listarLenguajes$0$0(<generated>)
at org.ibit.rol.sac.persistence.delegate.IdiomaDelegateImpl$$EnhancerByCGLIB$$2abe3ec$$FastClassByCGLIB$$5061d595.invoke(<generated>)
at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:201)
at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.intercept(DelegateLogInterceptor.java:91)
at org.ibit.rol.sac.persistence.delegate.IdiomaDelegateImpl$$EnhancerByCGLIB$$2abe3ec.listarLenguajes(<generated>)
at org.ibit.rol.sac.persistence.delegate.IdiomaDelegate.listarLenguajes(IdiomaDelegate.java:60)
at es.caib.rolsac.back2.util.RolsacSessionListener.sessionCreated(RolsacSessionListener.java:23)
at org.apache.catalina.session.StandardSession.tellNew(StandardSession.java:383)
at org.apache.catalina.session.StandardSession.setId(StandardSession.java:355)
at org.apache.catalina.session.ManagerBase.createSession(ManagerBase.java:703)
at org.apache.catalina.session.StandardManager.createSession(StandardManager.java:313)
at org.apache.coyote.tomcat5.CoyoteRequest.doGetSession(CoyoteRequest.java:2274)
at org.apache.coyote.tomcat5.CoyoteRequest.getSession(CoyoteRequest.java:2116)
at org.apache.coyote.tomcat5.CoyoteRequestFacade.getSession(CoyoteRequestFacade.java:528)
at org.apache.catalina.authenticator.AuthenticatorBase.getSession(AuthenticatorBase.java:692)
at es.caib.loginModule.auth.SeyconAuthenticator.authenticate(SeyconAuthenticator.java:128)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:118)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:34)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:54)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:929)
at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:160)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:799)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:705)
at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:577)
at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
at java.lang.Thread.run(Thread.java:745)
2017-07-11 12:24:21,506 ERROR [es.caib.rolsac.back2.util.UAServletFilter] Error al cercar els idiomes de la base de dades - org.ibit.rol.sac.persistence.delegate.DelegateException: java.rmi.ServerError: Unexpected Error:; nested exception is: 
java.lang.IllegalAccessError: org/apache/commons/collections/ReferenceMap$Entry
```

**Comment by slromero-indra** [comment]
Hemos realizado una primera búsqueda en nuestro JBoss3 para ver las versiones que hay de commons collections:
 
![captura](https://user-images.githubusercontent.com/17451407/28070044-eff7951a-664b-11e7-920c-c03e3de55634.png)

El jar que aparece es el de JBoss (versión 2.1)

Seguimos investigando el problema.

**Comment by rsanz-indra** [comment]
En cuanto al método es.caib.rolsac.back2.util.RolsacSessionListener.sessionCreated(HttpSessionEvent) no es la razón del error (esa clase en cuestión se usa para contear las sesiones web). Los errores se producen cuando desde los módulos web se intenta acceder a la capa de EJBs, los primeros errores que salen son los debidos a clases que se inicializan (filtros web, request listeners, etc.).  El error de IllegalAccessError se suele producir cuando hay diferentes versiones de una misma librería.

**Comment by sgelabert-dgtic** [comment]
Sistemes em retorna aquest resultat:
` deploy/jbossweb-tomcat50.sar/commons-collections.jar Versión: 2.1 Tamaño: 165119 Fecha: ago 27 2014 `

**Comment by rsanz-indra** [comment]
Lo único que se nos ocurre es meter esa librería al ear ya que está en modo isolated.
Otra opción es ver si nos podéis pasar el JBoss de PRO para echarle un vistazo y hacer pruebas.

**Comment by sgelabert-dgtic** [comment]
Entenc que no heu pogut reproduir el problema en el vostre entorn. Opcions:
a) Tenir un entorn on testejar i on poder reproduir el problema:
- Recentement s'ha aplicat un nou parche de seycon als Jboss 3.2.8-caib18, he sol·licitat que em passin el parche per tenir un entorn identic al de pro. Voltros el teniu aplicat a caibter?
- Demanar la clonació de l'entorn de PRO sobre una màquina virtual de desenvolupament. Això serà més costos en temps...
b) Ficar la llibreria commons-collections.jar dins l'ear i provar a PRE i a PRO
c) Migrar ROLSAC 1.5.4 a Jboss 5.2 (d'entrada ho descartaria per no ficar més entropia)

**Comment by rsanz-indra** [comment]
No, en nuestro entorno no se ha producido ninguna vez. En caibter no se ha instalado dicho parche, estaría bien que nos lo pasarais para tenerlo instalado.
Por lo que dices en PRE no está instalado ese parche, no? Si es así, si te parece esperamos a que instalen el parche en PRE y probamos a ver.

**Comment by sgelabert-dgtic** [comment]
S'ha aplicat un nou parche als servidors Jboss-3.2.8 de PREproducció i PROducció i d'entrada ha desplegat bé en els dos entorns.
He sol·licitat que s'apliqui el parche també sobre el nou entorn Jboss 5.2 i que se'ns distribueixi el parche per aplicar-ho als nostres entorns de desenvolupament.
