### ISSUE TITLE
Bug traspàs de normativa

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#417]
Error al intentar desar una normativa traspassada des del BOIB. Adjunt captura de pantalla
L'error es produeix quan la norma té un titol massa llarg i s'intenta actualitzar la taula d'Historic
```
Caused by: java.sql.BatchUpdateException: ORA-12899: el valor es demasiado grande para la columna "ROLSAC"."RSC_HISTOR"."HIS_NOMBRE" (real: 551, máximo: 512)

	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10345)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at org.jboss.resource.adapter.jdbc.WrappedStatement.executeBatch(WrappedStatement.java:779)
	at net.sf.hibernate.impl.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:54)
	at net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:128)
	... 100 more
```
Cal truncar el titol de la norma perquè no es produeixi aquest error.
![captura](https://user-images.githubusercontent.com/17268396/31437667-52e78130-ae86-11e7-8c36-9c70e50df1b4.jpg)

![captura 2](https://user-images.githubusercontent.com/17268396/31437601-1c108c56-ae86-11e7-9be7-3ed95211ea65.jpg)

**Comment by slromero-indra** [comment]
El error se produce en el campo nombre en la tabla histórico y se podría producir en cualquier entidad (normativa, ficha, procedimiento....). Tras revisar en cada una de las entidades, se ha tomado la decisión de acortar el nombre (sin importar el nombre) a un máximo de 512 caracteres.
