### ISSUE TITLE
Enviament de procediments interns a SIA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#431]
Es sol·licita incorporar una utilitat per integrar amb SIA procediments administratius no publicats a la Seu Electrònica (Estat: Intern o d'elaboració). Des del punt de vista de SIA, els procediment quedarien amb estat "NO ACTIU"

**Comment by dmadronal-indra** [comment]
Buenas,
¿Podemos iniciar la tarea?

**Comment by dmadronal-indra** [comment]
Añadimos los comentarios tratados por correo.

A priori, únicament s'establiria el nivell d'administració electrònica a un valor predeterminada en cas que no existeixi un tràmit d'inici. La resta de valors es tindran emplenats.
Tal com s'ha plantejat aquesta funcionalitat, aquestes actualitzacions no entren dins de cap procés automàtic, són peticions que es realitzen manualment. S'entén que per a aquests procediments que requereixin codi SIA abans de ser publicats a la seu, es realitzaran les peticions de forma manual per obtenir o actualitzar les dades.

**Comment by sgelabert-dgtic** [comment]
La DGTIBG finalment veu bé l'aplicació del canvi. 
Es sol·licta però actualitzar el document d'estimació de la tasca per incloure l'enviament també de Serveis Administratius. **La tasca romandrà bloquejada fins que la DGTIBG doni el vist i plau al nou document d'estimació**

**Comment by bgarcia-dgtic** [comment]
Hola,
He fet proves i pareix que funciona correctament, es a dir, quan premo el botó "ENVIA SIA - NO ACTIU" obtinc el codi SIA però l'estat queda como "Baixa" i hauria de ser "No actiu".

**Comment by sgelabert-dgtic** [comment]
Ens interessaria poder passar a producció la versió 1.7.1 aquesta setmana. Podríeu revisar el canvi de nomenclatura ?
Gràcies

**Comment by episano-dgtic** [comment]
Un par de cosas más:
1) El cambio de estado alta/baja a activo/no activo, se debe aplicar también a todos los procedimientos/servicios de la base de datos, no sólo a los nuevos. 
2) Antes de salir el botón de envio de sia, sale un mensaje de tiene cambios sin guardar. 
![enviosinguardar_mensajesalida](https://user-images.githubusercontent.com/17451683/50763716-e2aaeb00-1270-11e9-9c0e-cea4a6a23c72.gif)
Es obvio que se desea enviar los datos a sia actualizados, y queda demasiado redundante dos mensajes uno de salida y otro de envio a sia. Podéis evitar salga el primer mensaje, ojo si sale del procedimiento debe salir dicho mensaje. 
3) Podríais cambiar la máscara del campo de la fecha de act. de SIA, para que aparezca tb. la hora de envio. Es que si se hacen varios cambios en un día, no se puede saber si se ha enviado los últimos datos a SIA. 
4) En los servicios, si tienen un documento adjunto da un error"traducciondocumento" al enviar los datos a SIA y no obtenemos el código de sia:
![envioservicio_anexos_mensajeerror](https://user-images.githubusercontent.com/17451683/50763884-61a02380-1271-11e9-9c2f-86745fa931ae.gif)
`11:43:19,251 ERROR [org.jboss.ejb.plugins.LogInterceptor] (http-10.215.9.184-18080-9) RuntimeException in method: public abstract org.ibit.rol.sac.model.Servicio org.ibit.rol.sac.persistence.intf.ServicioFacade.obtenerServicio(java.lang.Long) throws java.rmi.RemoteException:
java.lang.ClassCastException: org.ibit.rol.sac.model.TraduccionDocumentoServicio cannot be cast to org.ibit.rol.sac.model.TraduccionDocumento
	at org.ibit.rol.sac.persistence.ejb.ServicioFacadeEJB.obtenerServicio(ServicioFacadeEJB.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.invocation.Invocation.performCall(Invocation.java:397)
	at org.jboss.ejb.StatelessSessionContainer$ContainerInterceptor.invoke(StatelessSessionContainer.java:233)
	at org.jboss.resource.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnectionInterceptor.java:156)
	at org.jboss.ejb.plugins.StatelessSessionInstanceInterceptor.invoke(StatelessSessionInstanceInterceptor.java:173)
	at org.jboss.ejb.plugins.CallValidationInterceptor.invoke(CallValidationInterceptor.java:63)
	at org.jboss.ejb.plugins.AbstractTxInterceptor.invokeNext(AbstractTxInterceptor.java:121)
	at org.jboss.ejb.plugins.TxInterceptorCMT.runWithTransactions(TxInterceptorCMT.java:350)
	at org.jboss.ejb.plugins.TxInterceptorCMT.invoke(TxInterceptorCMT.java:181)
	at org.jboss.ejb.plugins.SecurityInterceptor.process(SecurityInterceptor.java:281)
	at org.jboss.ejb.plugins.SecurityInterceptor.invoke(SecurityInterceptor.java:211)
	at org.jboss.ejb.plugins.security.PreSecurityInterceptor.process(PreSecurityInterceptor.java:167)
	at org.jboss.ejb.plugins.security.PreSecurityInterceptor.invoke(PreSecurityInterceptor.java:84)
	at org.jboss.ejb.plugins.LogInterceptor.invoke(LogInterceptor.java:205)
	at org.jboss.ejb.plugins.ProxyFactoryFinderInterceptor.invoke(ProxyFactoryFinderInterceptor.java:138)
	at org.jboss.ejb.SessionContainer.internalInvoke(SessionContainer.java:650)
	at org.jboss.ejb.Container.invoke(Container.java:1092)
	at sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
	at org.jboss.invocation.local.LocalInvoker$MBeanServerAction.invoke(LocalInvoker.java:169)
	at org.jboss.invocation.local.LocalInvoker.invoke(LocalInvoker.java:118)
	at org.jboss.invocation.InvokerInterceptor.invokeLocalMarshalled(InvokerInterceptor.java:346)
	at org.jboss.invocation.MarshallingInvokerInterceptor.invoke(MarshallingInvokerInterceptor.java:61)
	at org.jboss.proxy.TransactionInterceptor.invoke(TransactionInterceptor.java:61)
	at org.jboss.proxy.ejb.SecurityContextInterceptor.invoke(SecurityContextInterceptor.java:64)
	at org.jboss.proxy.SecurityInterceptor.invoke(SecurityInterceptor.java:68)
	at org.jboss.proxy.ejb.StatelessSessionInterceptor.invoke(StatelessSessionInterceptor.java:112)
	at org.jboss.proxy.ClientContainer.invoke(ClientContainer.java:101)
	at com.sun.proxy.$Proxy613.obtenerServicio(Unknown Source)
	at org.ibit.rol.sac.persistence.delegate.ServicioDelegate.obtenerServicio(ServicioDelegate.java:67)
	at org.ibit.rol.sac.persistence.delegate.ServicioDelegate$$EnhancerByCGLIB$$7bbaf480.CGLIB$obtenerServicio$9(<generated>)
	at org.ibit.rol.sac.persistence.delegate.ServicioDelegate$$EnhancerByCGLIB$$7bbaf480$$FastClassByCGLIB$$5d8f6db9.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.intercept(DelegateLogInterceptor.java:91)
	at org.ibit.rol.sac.persistence.delegate.ServicioDelegate$$EnhancerByCGLIB$$7bbaf480.obtenerServicio(<generated>)
	at es.caib.rolsac.back2.controller.CatalegServeisBackController.checkEnvioSiaNoActivo(CatalegServeisBackController.java:909)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at es.caib.rolsac.back2.util.UAServletFilter.doFilter(UAServletFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at es.caib.rolsac.back2.util.LocaleServletFilter.doFilter(LocaleServletFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:183)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:534)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31)
	at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:60)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:599)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451)
	at java.lang.Thread.run(Thread.java:745)`
5) Pendiente ver que ocurre con el procedimiento 3286693 que es público de futura visualización, ya que no parece en el envio de

**Comment by slromero-indra** [comment]
Ya hemos realizado todos los cambios del 1 al 4.

Respecto al punto 5, procedimiento 3286693, si por alguna razón no ha entrado al ciclo, con sólo guardar (por ejemplo, añadiendo un espacio a algún campo de texto), debería de entrar en el ciclo (si no entra, debe tener algún dato pendiente por rellenar o debéis pasarnos el log por si hay algún problema oculto)

**Comment by episano-dgtic** [comment]
Hemos visto que no hay problema con la futura publicación de procedimientos, que era el caso del 328693. Pero si ha problemas para los procedimientos/servicios que caducan, ya que no cambian el estado a no activo/baja.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado pruebas en nuestro entorno y no hemos sido capaces de replicar el problema. Por favor, enviadnos info de algunos procedimientos. Os pasamos las consultas a ejecutar, puede que bien tenga algún problema el procedimiento o bien el procedimiento esté en la lista de pendientes con algún problema no observado:

 ```
select * 
  from rsc_siapdt where sip_idelem IN (ID_PROCS);
  
  select * 
   from rsc_proced where pro_codi in (ID_PROCS);
```

**Comment by episano-dgtic** [comment]
Efectivamente el procedimiento 3280064, ha pasado a no activo, corretamente.
