### ISSUE TITLE
Bug: error traspàs del BOIB

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#474]
Hola,

El BOIB han migrat l'aplicació del JBOSS3 al JBOSS5 i ara dóna error a l'hora de fer el traspas del BOIB.
![imatge](https://user-images.githubusercontent.com/26536678/108200663-0fec4780-711f-11eb-966b-ab5b7daeeb82.png)

**Comment by slromero-indra** [comment]
Buenas, para poder replicar el problema:
 - Nos podéis pasar los parámetros que utilizáis en el traspaso?
 - Se produce algún error por jboss o javascript? 
 - La migración de la BOIB de jboss3 a jboss5 está en producción o solo en proves?

**Comment by episano-dgtic** [comment]
El error da: 

2021-02-17 10:02:06,160 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/rolsacback].[rolsacmvc]] (http-10.215.9.184-18080-11) Servlet.service() para servlet rolsacmvc lanzó excepción
java.lang.NullPointerException
	at org.ibit.rol.sac.persistence.eboib.EBoibSearchNormativa.populateBoibResult(EBoibSearchNormativa.java:328)
	at org.ibit.rol.sac.persistence.eboib.EBoibSearchNormativa.makeSearch(EBoibSearchNormativa.java:145)
	at es.caib.rolsac.back2.controller.NormativaBackController.llistatEnviamentsBoib(NormativaBackController.java:584)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at es.caib.rolsac.back2.util.UAServletFilter.doFilter(UAServletFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at es.caib.rolsac.back2.util.LocaleServletFilter.doFilter(LocaleServletFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:183)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:534)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31)
	at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:60)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:599)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bgarcia-dgtic** [comment]
La migració de jboss3 a jboss5 està en producció.
Els paràmetre que utilitzo a l'hora de fer la cerca és posar al camp "Num. Butlletí" el valor "023/2021"

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado multiples pruebas y revisado el código,lo único que se nos ha ocurrido es que se haya modificado la ruta de acceso, ¿Es posible que ahora vaya por https? en nuestros entornos hemos probado a modificar la url del boib para que vaya por https y parece que está respondiendo. ¿Podeis verificar si esto solventa el problema en vuestros entornos?  

es.caib.rolsac.traspasboib.url=**https**://www.caib.es/eboibfront/

**Comment by bgarcia-dgtic** [comment]
He fet el canvi i pareix que funciona
