### ISSUE TITLE
Bug acceso API

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#475]
Hola,
Al intentar acceder en ROLSAC al wsdl  está dando un error.

{http://xml.apache.org/axis/}stackTrace:java.lang.ClassNotFoundException: es.caib.rolsac.api.v2.enllac.ejb.intf.EnllacTelematicoQueryServiceEJBRemote from BaseClassLoader@45436e66{vfszip:/D:/Doc/AAPP/JBOSS/jboss5/jboss-as/server/default/deploycaib/rolsac.ear/}
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:481)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.axis.utils.ClassUtils$2.run(ClassUtils.java:187)
![imatge](https://user-images.githubusercontent.com/26536678/108335536-5e5b1e00-71d3-11eb-9221-d24f1c847b6f.png)

**Comment by bgarcia-dgtic** [comment]
funciona correctament
